FROM ubuntu:22.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
        git python3 python3-pip \
        build-essential libssl-dev zlib1g-dev libcurl4-openssl-dev libexpat-dev gettext coreutils sudo && \
  pip install flake8

# 2.39.x / 2.38.x: latest available version / Rolling distros / Fedora 36 and 37
# 2.31.x: Rocky Linux 8 and 9
# 2.36.x: Alpine
# 2.35.x: openSUSE 15.4
# 2.34.x: Ubuntu 22.04
# 2.31.x: Rocky Linux 8 and 9 / AlmaLinux 8 and 9 / CentOS 9 Stream
# 2.30.x: Debian 11
# 2.27.x: CentOS 8 / CentOS 8 Stream
# 2.26.x: openSUSE 15.3
# 2.25.x: Ubuntu 20.04
# 2.20.x: Debian 10
ENV GIT_VERSIONS="v2.39.0 v2.38.1 v2.25.5 v2.20.5"
RUN git clone https://github.com/git/git && cd git && \
  for v in $GIT_VERSIONS; do \
    git checkout $v && \
    vv=${v%.*}.x && \
    NO_TCLTK=1 make prefix=/usr/local/git-$vv -j$(nproc) && \
    NO_TCLTK=1 make prefix=/usr/local/git-$vv install; \
  done && cd - && rm -rf git
RUN git config --global user.name "CI Bot" && \
  git config --global user.email "ci@git-pile.github.io" && \
  git config --global init.defaultBranch master
RUN id
RUN git clone --depth 1 --branch v1.7.0 https://github.com/bats-core/bats-core.git && \
  /bats-core/install.sh /usr && rm -rf bats-core
LABEL org.opencontainers.image.source=https://github.com/git-pile/git-pile
