#!/usr/bin/python3
# PYTHON_ARGCOMPLETE_OK
# SPDX-License-Identifier: LGPL-2.1+

import git_pile.git_mbox_prepare as git_mbox_prepare
import sys


if __name__ == "__main__":
    sys.exit(git_mbox_prepare.main(*sys.argv[1:]))
