# SPDX-License-Identifier: LGPL-2.1+
from __future__ import annotations

import os
import pathlib


PREAMBLE_COMMENT = """
# This rebase-todo was generated by git-merge-range.
#
# Conflicts are presented with the usual makers: "<<<<<<< OURS" for the start of
# commits in the current range; "=======" to delimit the end of OURS and the
# start of commits from the other range; and ">>>>>>> THEIRS" to mark the end.
#
# In order to help conflict resolution and overall review of the todo list, some
# commits contain "# INFO: ..." lines just above them. "# INFO: OURS" and "#
# INFO: THEIRS" indicates that the commit comes from the current or the other
# range, respectively. If the commit matches other commits "diff-wise", suffixes
# in the format " == <ORIGIN>(<sha1>...)" are added to those lines, where
# <ORIGIN> could be "OURS", "THEIRS" or "BASE".
"""


def run_rebase_seq_editor(generated_todo_path: str, original_todo_path: str) -> None:
    try:
        original_lines = pathlib.Path(original_todo_path).read_text().splitlines()
        original_instructions = []
        i = len(original_lines) - 1
        while i >= 0:
            if not original_lines[i].startswith("#"):
                break
            i -= 1
        original_instructions = original_lines[i + 1 :]

        generated = pathlib.Path(generated_todo_path).read_text().splitlines()

        out = PREAMBLE_COMMENT.strip().splitlines()
        out.append("")
        out.extend(generated)
        out.extend(original_instructions)

        pathlib.Path(original_todo_path).write_text("\n".join(out) + "\n")
    finally:
        try:
            os.unlink(generated_todo_path)
        except:
            pass
