name: build-test

on:
  push:
    branches: [ ci, master ]
  pull_request:
    branches: [ ci, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}

      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --exclude setup.py --extend-ignore E722,W605 --show-source --statistics

      - name: Test venv installation
        run: |
          python3 -m venv testvenv
          testvenv/bin/python3 -m pip install .
          testvenv/bin/git-pile -v
          rm -r testvenv

      - name: Test user installation
        run: |
          python3 -m pip install --user .
          git-pile -v
          python3 -m pip uninstall --yes git-pile

      - name: Test editable user installation
        run: |
          python3 -m pip install --user --editable .
          git-pile -v

      - name: Test git PATH integration
        run: |
          git pile --version

      - name: Test uninstalled git-pile
        run: |
          python3 -m pip uninstall --yes git-pile
          export PATH=$PWD:$PATH
          git pile --version
