name: build-test

on:
  push:
    branches: [ ci, master ]
  pull_request:
    branches: [ ci, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}

      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --exclude setup.py --extend-ignore E722,W605 --show-source --statistics

      - name: Test venv installation
        run: |
          python3 -m venv testvenv
          testvenv/bin/python3 -m pip install .
          testvenv/bin/git-pile -v
          rm -r testvenv

      - name: Test user installation
        run: |
          python3 -m pip install --user .
          git-pile -v
          python3 -m pip uninstall --yes git-pile

      - name: Test editable user installation
        run: |
          python3 -m pip install --user --editable .
          git-pile -v

      - name: Test git PATH integration
        run: |
          git pile --version

      - name: Test uninstalled git-pile
        run: |
          python3 -m pip uninstall --yes git-pile
          export PATH=$PWD:$PATH
          git pile --version

  integration-tests:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/git-pile/builder:test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    strategy:
      matrix:
        python-version: [ '3.7', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Export PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v3
        with:
          repository: bats-core/bats-core
          ref: v1.7.0
          path: test/bats-core
      - run: test/bats-core/install.sh $HOME/.local

      - name: Install git-pile
        run: python3 -m pip install --user .

      - name: Setup git
        run: |
          git config --global user.name "ci"
          git config --global user.email "ci@git-pile.github.io"
          git config --global init.defaultBranch master

      # User in the container will be root, but the cloned repo is owned by the
      # user running github-runner. Git doesn't like that as the repo will then
      # be unusable by the owner:  we don't care about it since this is only
      # used for running these tests.
      #
      # See https://github.com/actions/runner/issues/2033
      - name: Workaround directory permissions
        run: git config --global --add safe.directory $PWD

      - name: Run tests (git from distro)
        run: |
          git --version
          bats --print-output-on-failure --show-output-of-passing-tests --tap -T test

      - name: Run tests (git v2.25.x)
        run: |
          export PATH=/usr/local/git-2.25.x:$PATH
          git --version
          bats --print-output-on-failure --show-output-of-passing-tests --tap -T test

      - name: Run tests (git v2.38.x)
        run: |
          export PATH=/usr/local/git-2.38.x:$PATH
          git --version
          bats --print-output-on-failure --show-output-of-passing-tests --tap -T test
