name: build-test

on:
  push:
    branches: [ ci, master ]
  pull_request:
    branches: [ ci, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82,F841 --show-source --statistics

      - name: Install
        run:  python -m pip install -e .

      - name: Sanity check - run
        run: git pile --version
