name: build-test

on:
  push:
    branches: [ ci, master ]
  pull_request:
    branches: [ ci, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}

      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --exclude setup.py --extend-ignore E722,W605 --show-source --statistics

      - name: Test venv installation
        run: |
          python3 -m venv testvenv
          testvenv/bin/python3 -m pip install .
          testvenv/bin/git-pile -v
          rm -r testvenv

      - name: Test user installation
        run: |
          python3 -m pip install --user .
          git-pile -v
          python3 -m pip uninstall --yes git-pile

      - name: Test editable user installation
        run: |
          python3 -m pip install --user --editable .
          git-pile -v

      - name: Test git PATH integration
        run: |
          git pile --version

      - name: Test uninstalled git-pile
        run: |
          python3 -m pip uninstall --yes git-pile
          export PATH=$PWD:$PATH
          git pile --version

  integration-tests:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/git-pile/builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    strategy:
      matrix:
        python-version: [ '3.7', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Export PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v3
        with:
          repository: bats-core/bats-core
          ref: v1.7.0
          path: test/bats-core
      - run: test/bats-core/install.sh $HOME/.local

      - name: Use git-pile from checkout
        run: echo "$PWD" >> $GITHUB_PATH

      - name: Setup git
        run: |
          git config --global user.name "ci"
          git config --global user.email "ci@git-pile.github.io"
          git config --global init.defaultBranch master

      # User in the container will be root, but the cloned repo is owned by the
      # user running github-runner. Git doesn't like that as the repo will then
      # be unusable by the owner:  we don't care about it since this is only
      # used for running these tests.
      #
      # See https://github.com/actions/runner/issues/2033
      - name: Workaround directory permissions
        run: git config --global --add safe.directory $PWD

      - name: Enable coverage
        if: ${{ matrix.python-version == '3.10' }}
        run: echo "COVERAGE=1" >> $GITHUB_ENV

      - name: Run tests (git from distro)
        run: |
          git --version
          echo "TAP version 13\r" > git.tap
          bats --tap -T test | tee -a git.tap

      - name: Run tests (git v2.25.x)
        if: always()
        run: |
          export PATH=/usr/local/git-2.25.x:$PATH
          git --version
          echo "TAP version 13\r" > git-2.25.tap
          bats --tap -T test | tee -a git-2.25.tap

      - name: Run tests (git v2.38.x)
        if: always()
        run: |
          export PATH=/usr/local/git-2.38.x:$PATH
          git --version
          echo "TAP version 13\r" > git-2.38.tap
          bats --tap -T test | tee -a git-2.38.tap

      - name: Generate test summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "*.tap"

      # Since coverage is only reported in git-pile itself, there is no need
      # to report it for all python version - use just one of them
      - name: Coverage results
        if: ${{ matrix.python-version == '3.10' }}
        run: |
          coverage report --include=git_pile/* | tee report.txt
          echo "## Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
          cat report.txt >> $GITHUB_STEP_SUMMARY
          echo \`\`\` >> $GITHUB_STEP_SUMMARY
          coverage html --include=git_pile/*

      - name: Upload coverage
        if: ${{ matrix.python-version == '3.10' }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: htmlcov/
